# The following services are mandatories for a Fonos deployment

services:

  apiserver:
    extends:
      file: common.yml
      service: common
    image: ${AS_IMAGE}
    # TODO: Fix health check conflict with the new interceptor
    healthcheck:
      test: ["CMD-SHELL", "echo removethis"]
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      DS_HOST: ${DS_HOST}
      DS_PORT: ${DS_PORT}
      DS_SECRET: ${DS_SECRET}
      DS_AUTH_USERNAME: ${DS_AUTH_USERNAME}
      DS_AUTH_SECRET: ${DS_AUTH_SECRET}
      DS_AUTH_HOST: ${DS_AUTH_HOST}
      DS_AUTH_PORT: ${DS_AUTH_PORT}
      DS_AUTH_DB: ${DS_AUTH_DB}
      # Warning: Temporal variable
      FS_HOST: ${FS_HOST_PUBLIC}
      FS_PORT: ${FS_PORT}
      FS_USERNAME: ${FS_USERNAME}
      FS_SECRET: ${FS_SECRET}
      FS_DEFAULT_STORAGE_BUCKET: ${FS_DEFAULT_STORAGE_BUCKET}
      EVENTS_BROKERS: amqp://${EB_USERNAME}:${EB_SECRET}@${EB_HOST}:${EB_PORT}
      SIPPROXY_HOST: ${SIPPROXY_HOST}
      SIPPROXY_API_PORT: ${SIPPROXY_API_PORT}
      SIPPROXY_API_USERNAME: ${SIPPROXY_API_USERNAME}
      SIPPROXY_API_SECRET: ${SIPPROXY_API_SECRET}
      LOGS_DRIVER_HOST: ${LOGS_DRIVER_HOST}
      LOGS_DRIVER_PORT: ${LOGS_DRIVER_PORT}
      MS_ENDPOINT: ${MS_ENDPOINT}
      MS_TRUNK: ${MS_TRUNK}
      MS_CONTEXT: ${MS_CONTEXT}
      MS_EXTENSION: ${MS_EXTENSION}
      MS_ARI_URL: ${MS_ARI_URL}
      MS_ARI_USERNAME: ${MS_ARI_USERNAME}
      MS_ARI_SECRET: ${MS_ARI_SECRET}
      LOG_OPT_TAG_PREFIX: ${LOG_OPT_TAG_PREFIX}
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
    ports:
      - ${APISERVER_PORT}:${APISERVER_PORT}
    logging:
      options:
        tag: ${LOG_OPT_TAG_PREFIX}.${COMPOSE_PROJECT_NAME}.apiserver
    networks:
      fonos:
        aliases:
          - ${APISERVER_ENDPOINT}
    secrets:
      - source: jwt.salt
        target: /home/fonos/.fonos/jwt.salt

  datasource:
    extends:
      file: common.yml
      service: common 
    image: ${DS_IMAGE}
    deploy:
      placement:
        constraints: [node.role == manager]    
    command: ['redis-server', '/etc/redis/redis.conf' ]
    healthcheck:
      test: ['CMD', 'redis-cli','ping']
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      options:
        tag: ${LOG_OPT_TAG_PREFIX}.${COMPOSE_PROJECT_NAME}.datasource
    networks:
      fonos:
        aliases: 
          - ${DS_HOST}
    configs:
      - source: redis.conf
        target: /etc/redis/redis.conf
    volumes: 
      - datasource:/data

  datasource_auth:
    extends:
      file: common.yml
      service: common 
    image: ${DS_AUTH_IMAGE}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DS_AUTH_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DS_AUTH_SECRET}
      MONGO_INITDB_DATABASE: ${DS_AUTH_DB}
    deploy:
      placement:
        constraints: [node.role == manager]
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      options:
        tag: ${LOG_OPT_TAG_PREFIX}.${COMPOSE_PROJECT_NAME}.datasource_auth
    networks:
      fonos:
        aliases: 
          - ${DS_AUTH_HOST}
    configs:
      - source: init_mongo.js
        target: /docker-entrypoint-initdb.d/init-mongo.js
    volumes: 
      - datasource_auth:/data/db

  eventsbroker:
    extends:
      file: common.yml
      service: common 
    image: ${EB_IMAGE}
    environment:
      RABBITMQ_USERNAME: ${EB_USERNAME}
      RABBITMQ_PASSWORD: ${EB_SECRET}
      RABBITMQ_NODE_PORT_NUMBER: ${EB_PORT}
    logging:
      options:
        tag: ${LOG_OPT_TAG_PREFIX}.${COMPOSE_PROJECT_NAME}.eventsbroker
    networks:
      fonos:
        aliases: 
          - ${EB_HOST}
