name: release
on:
  push:
    paths:
    - 'mods/**'
    branches:
    - main
    - dev
  #release:
  #  types: [published]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(node -e "console.log(require('./lerna.json').version)")
    - name: Publish to Docker Hub the Providers API
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: fonoster/fonos-providers
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        workdir: mods/providers
        tags: "latest, ${{ steps.get_version.outputs.VERSION }}"
